### ISSUE TITLE
CDE Speaker Topic gist

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#13]
Title - The Journey to Success: Your First Few Thousand Stores
File 
[The Journey to Success_ Your First Few Thousand Stores.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4015617/The.Journey.to.Success_.Your.First.Few.Thousand.Stores.docx)

@LopaParmarBTN please take images from @DarshanGangwaniBTN

**Comment by LopaParmarBTN** [comment]
@DarshanGangwaniBTN please help me with the speaker's image.

**Comment by LopaParmarBTN** [comment]
content posted. Waiting for image.

**Comment by LopaParmarBTN** [comment]
https://cannabisdrinksexpo.com/en/blog/insights-68/the-journey-to-success-your-first-few-thousand-stores-177.htm

Please check.
