### ISSUE TITLE
USA Spirits Ratings Insights - Build a digital marketing strategy you can be known for

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#15]
Platform - USR
File - 
[Build a digital marketing strategy you can be known for.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4018862/Build.a.digital.marketing.strategy.you.can.be.known.for.docx)

@LopaParmarBTN please help me with a header image for this, and maybe one or two images for content as well. Thanks

**Comment by LopaParmarBTN** [comment]
https://usaspiritsratings.com/en/blog/insights-1/building-a-digital-marketing-strategy-that-you-can-be-known-for-122.htm
