### ISSUE TITLE
CDE Speaker Brief - Hannah Davis 

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#16]
File - 
[What does a Great Distribution Partner in Cannabis Look Like.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4019138/What.does.a.Great.Distribution.Partner.in.Cannabis.Look.Like.docx)

@LopaParmarBTN please take images from @DarshanGangwaniBTN

**Comment by LopaParmarBTN** [comment]
@DarshanGangwaniBTN working on the image. will upload this as soon as I get images.

**Comment by ghost** [comment]
@LopaParmarBTN Completed with the image. Please upload.

**Comment by LopaParmarBTN** [comment]
https://cannabisdrinksexpo.com/en/blog/insights-68/what-does-a-great-distribution-partner-in-cannabis-look-like-178.htm
