### ISSUE TITLE
London Comp Activities

### ISSUE THREAD

**Issue by RashikaBTN** [RashikaBTN/Digital-Marketing-Team#21]
Beverage Trade Network DM instagram - @KartikDesaiBTN 
Linkedin DM 20 - @chinkabtn 
BTN News Announcements & Distribution - @AmiSmith @chinkabtn 
IBWSS UK dm instagram - @DevanshiTanejaBTN

**Comment by ghost** [comment]
- [ ] Instagram DM BTN -> 5/day (Kartik)

**Comment by ghost** [comment]
Linkedin, Instagram DM from Bevroute, LC and Top 100 accounts.
