### ISSUE TITLE
comexposium x vinexpo

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#26]
Attaching article here. 
Ready to upload on btn news, sca news, and london comps news @LopaParmarBTN @AmiSmith 

File - 
[Vinexpo Holding and Comexposium Merge To Create Premier Wine & Spirits Business.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4038928/Vinexpo.Holding.and.Comexposium.Merge.To.Create.Premier.Wine.Spirits.Business.docx)

**Comment by ghost** [comment]
Also please let social media team know once it's uploaded.

**Comment by LopaParmarBTN** [comment]
https://londonspiritscompetition.com/en/blog/news-3/vinexpo-holding-and-comexposium-merge-to-build-a-premier-wine-spirits-business-206.htm

https://londonwinecompetition.com/en/blog/news-2/vinexpo-holding-and-comexposium-merge-to-build-a-premier-wine-spirits-business-304.htm

**Comment by ghost** [comment]
https://sommelierschoiceawards.com/en/blog/news-2/vinexpo-holding-and-comexposium-merge-to-build-a-premier-wine-spirits-business-268.htm sca uploaded

https://bartenderspiritsawards.com/en/blog/news-3/vinexpo-holding-and-comexposium-merge-to-build-a-premier-wine-spirits-business-177.htm bsa uploaded

**Comment by AmiSmith** [comment]
Posted on btn
https://beveragetradenetwork.com/en/news/wine-74/vinexpo-holding-and-comexposium-merge-to-build-a-premier-wine-spirits-business-8983.htm
