### ISSUE TITLE
22nd Jan

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#38]
IBWSS PR - Book Your Exhibitor Table Before January 31 To Avail Special Pricing
File - 
[Book Your Exhibitor Table Before January 31 To Avail Special Pricing.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4095428/Book.Your.Exhibitor.Table.Before.January.31.To.Avail.Special.Pricing.docx)

**Comment by ghost** [comment]
CFS Landing Page
Live link - https://cannabisfoodshow.com/en/blog/insights-68/20-leading-cannabis-dispensaries-in-california-183.htm

**Comment by ghost** [comment]
SCA - Leveraging Wine Events To Build Sales Leads
File - 
[Leveraging Wine Events To Build Sales Leads.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4096704/Leveraging.Wine.Events.To.Build.Sales.Leads.docx) @AnjaliSisodiyaBTN

**Comment by LopaParmarBTN** [comment]
> IBWSS PR - Book Your Exhibitor Table Before January 31 To Avail Special Pricing
> File -
> [Book Your Exhibitor Table Before January 31 To Avail Special Pricing.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4095428/Book.Your.Exhibitor.Table.Before.January.31.To.Avail.Special.Pricing.docx)

https://ibwsshow.com/en/blog/news-66/book-your-exhibitor-table-before-january-31-to-avail-special-pricing-310.htm
