### ISSUE TITLE
London Drinks Guide Blog 1

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#4]
Platform - London Drinks Guide
Title - 10 Bottomless Brunches In London For The Perfect Buzz

File  - 
[10 Bottomless Brunches In London For The Perfect Buzz.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4009755/10.Bottomless.Brunches.In.London.For.The.Perfect.Buzz.docx)
(images in file) 

@RashikaBTN @LopaParmarBTN

**Comment by LopaParmarBTN** [comment]
![image](https://user-images.githubusercontent.com/47556118/71808391-af718680-3093-11ea-8be5-48e6e0655135.png)

**Comment by LopaParmarBTN** [comment]
Looks like backend ain't functional yet.

**Comment by ghost** [comment]
@KaranBTN

**Comment by KaranBTN** [comment]
https://londondrinksguide.com/en/articles/insights-1/10-bottomless-brunches-in-london-for-the-perfect-buzz-6.htm

Uploaded
