### ISSUE TITLE
All London PRS

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#47]
Last call

LWC - 
[Last Call To Enter Your Wines Into London Wine Competition.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4147953/Last.Call.To.Enter.Your.Wines.Into.London.Wine.Competition.docx)

Live: https://londonwinecompetition.com/en/blog/news-2/last-call-to-enter-your-wines-into-london-wine-competition-316.htm

LSC - 
[Last Call To Enter Your Spirits Into London Spirits Competition.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4147955/Last.Call.To.Enter.Your.Spirits.Into.London.Spirits.Competition.docx)

Live: https://londonspiritscompetition.com/en/blog/news-3/last-call-to-enter-your-spirits-into-london-spirits-competition-212.htm

LBC - 
[Last Call To Enter Your Beer Into London Beer Competition.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4147957/Last.Call.To.Enter.Your.Beer.Into.London.Beer.Competition.docx)

Live - https://londonbeercompetition.com/en/blog/news-2507/last-call-to-enter-your-beers-into-london-beer-competition-140.htm

**Comment by ghost** [comment]
Richard Siddle PR 

[London Wine Beer and Spirits Competitions to be promoted around the world.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4147959/London.Wine.Beer.and.Spirits.Competitions.to.be.promoted.around.the.world.docx)

https://londonwinecompetition.com/en/blog/news-2/london-wine-beer-and-spirits-competitions-to-be-promoted-around-the-world-319.htm
https://londonspiritscompetition.com/en/blog/news-3/london-wine-beer-and-spirits-competitions-to-be-promoted-around-the-world-215.htm
https://londonbeercompetition.com/en/blog/news-2507/london-wine-beer-and-spirits-competitions-to-be-promoted-around-the-world-142.htm

[London Wine, Beer, and Spirits Competitions launch Top 100 Lists.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4147964/London.Wine.Beer.and.Spirits.Competitions.launch.Top.100.Lists.docx)

https://londonwinecompetition.com/en/blog/news-2/london-wine-beer-and-spirits-competitions-launch-top-100-lists-317.htm
https://londonspiritscompetition.com/en/blog/news-3/london-wine-beer-and-spirits-competitions-launch-top-100-lists-214.htm
https://londonbeercompetition.com/en/blog/news-2507/london-wine-beer-and-spirits-competitions-launch-top-100-lists-141.htm

**Comment by ghost** [comment]
Combined London PR
[Last Call To Enter Into The London Competitions.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4151486/Last.Call.To.Enter.Into.The.London.Competitions.docx)

@AmiSmith

**Comment by RashikaBTN** [comment]
> Last Call To Enter Your Beer Into London Beer Competition.docx

@LopaParmarBTN upload and share the link once live please
all three

**Comment by RashikaBTN** [comment]
> Combined London PR
> [Last Call To Enter Into The London Competitions.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4151486/Last.Call.To.Enter.Into.The.London.Competitions.docx)
> 
> @AmiSmith

@AmiSmith  Upload this. but links are missing of a few things. like the units. please keep an eye for all thes places where we can add conversion link. and share once its live please

**Comment by AmiSmith** [comment]
Posted on btn
https://beveragetradenetwork.com/en/news/wine-74/last-call-to-enter-into-the-london-competitions-2020-9120.htm @chinkabtn @RashikaBTN
