### ISSUE TITLE
CFS ARTICLE UPLOAD - DEADLINE 12th FEB

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#50]
4 Things To Expect From The Cannabis Edibles Sector in 2020

File - 
[4 Things To Expect From The Cannabis Edibles Sector in 2020.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4185670/4.Things.To.Expect.From.The.Cannabis.Edibles.Sector.in.2020.docx)

@KaranBTN update me with live link once it's uploaded. Find appropriate header, and content images and get them approved by @LopaParmarBTN before uploading

**Comment by KaranBTN** [comment]
There are some High Priority Tasks & Priority Tasks there to be done, so unable to upload this by tomorrow, should I upload by end of this week?

**Comment by ghost** [comment]
@RashikaBTN please review Karan's task list so he can have the blog uploaded soon.

**Comment by KaranBTN** [comment]
https://cannabisfoodshow.com/en/blog/insights-68/4-things-to-expect-from-the-cannabis-edibles-sector-in-2020-189.htm

Published
