### ISSUE TITLE
CFS Interview Upload - Deadline 14th Feb

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#51]
File - 
[9 questions with flour child collective.docx](https://github.com/RashikaBTN/Digital-Marketing-Team/files/4202750/9.questions.with.flour.child.collective.docx)

Images - 
![FLOURCHILD_MAR2017_268](https://user-images.githubusercontent.com/49149328/74502944-50662380-4f15-11ea-9107-bac2e9444a55.jpg)
![FLOURCHILD_MAR2017_670](https://user-images.githubusercontent.com/49149328/74502948-51975080-4f15-11ea-981d-bbed85f3b16c.jpg)
![FLOURCHILD_MAR2017_679](https://user-images.githubusercontent.com/49149328/74502950-52c87d80-4f15-11ea-844b-36c5232a4f1b.jpg)
![Screen-Shot-2017-06-24-at-7 29 24-PM-228x300](https://user-images.githubusercontent.com/49149328/74502952-52c87d80-4f15-11ea-891c-699251381dd5.png)

**Comment by KaranBTN** [comment]
https://cannabisfoodshow.com/en/blog/interviews-92/9-questions-with-flour-child-collective-190.htm

Uploaded
