### ISSUE TITLE
June Task List

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#69]
Social : BSA + LDG
News finding for headlines (Twitter)
Article writing (Sid Pipeline)
Newsletters 4/week (2 sca + 2 bsa)
DM BSA+LDG
Blog/PR posting GDD + SCA
Mailchimp Data sorting and cleaning

**Comment by RashikaBTN** [comment]
please add Blog Submission for GDD & SCA

**Comment by RashikaBTN** [comment]
Mailchimp Database
