### ISSUE TITLE
Websites Weekly Review

### ISSUE THREAD

**Issue by ghost** [RashikaBTN/Digital-Marketing-Team#76]
Hi All,
Let's take 30 mins at the end of every Friday to review our websites, and please suggest whatever changes come to your mind that we should implement, as comments below in this same issue. 
@LopaParmarBTN @AnjaliSisodiyaBTN and @KartikDesaiBTN will go through these every Monday morning and see if the specified changes would be appropriate and possible to make on our end. If approved, we will go ahead with these changes.. 
End goal is to make the user experience as satisfying as possible.. So please explore the mobile versions as well.
Thank you,
Kartik

**Comment by ghost** [comment]
Include old 2019 and 2018 winners on our websites:

- [x] SCA
- [x] BSA
- [x] London Comps
- [x] USA Ratings

**Comment by LopaParmarBTN** [comment]
> Include old 2019 and 2018 winners on our websites:
> 
> * [x]  SCA
> * [x]  BSA
> * [x]  London Comps
> * [x]  USA Ratings

London Comps and USA Ratings Done
